(function() {var implementors = {};
implementors['vec_map'] = ["impl&lt;V: <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.VecMap.html' title='vec_map::VecMap'>VecMap</a>&lt;V&gt;","impl&lt;'a, V&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Iter.html' title='vec_map::Iter'>Iter</a>&lt;'a, V&gt;","impl&lt;'a, V&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Keys.html' title='vec_map::Keys'>Keys</a>&lt;'a, V&gt;","impl&lt;'a, V&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Values.html' title='vec_map::Values'>Values</a>&lt;'a, V&gt;",];implementors['ladspa'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ladspa/struct.Port.html' title='ladspa::Port'>Port</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='ladspa/enum.PortDescriptor.html' title='ladspa::PortDescriptor'>PortDescriptor</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ladspa/struct.ControlHint.html' title='ladspa::ControlHint'>ControlHint</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='ladspa/enum.DefaultValue.html' title='ladspa::DefaultValue'>DefaultValue</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='ladspa/struct.Properties.html' title='ladspa::Properties'>Properties</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
